twig:
    default_path: '%kernel.project_dir%/templates'
    # active le th√®me de formulaire bootstrap
    form_themes: ['bootstrap_5_layout.html.twig']
when@test:
    twig:
        strict_variables: true
